BuildFeed/Areas/admin/Controllers/RootController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BuildFeed.Controllers;
using BuildFeed.Model;

namespace BuildFeed.Admin.Controllers
{
    [Authorize(Roles = "Administrators")]
    [RouteArea("admin")]
    [RoutePrefix("")]
    public class RootController : BaseController
    {
        [Route("")]
        public ActionResult Index() => View();

        [Route("regen-cache")]
        public async Task<ActionResult> RegenerateCache()
        {
            var bRepo = new BuildRepository();
            await bRepo.RegenerateCachedProperties();

            return RedirectToAction(nameof(Index));
        }
    }
}

BuildFeed/Areas/admin/Controllers/metaController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BuildFeed.Admin.Models.ViewModel;
using BuildFeed.Controllers;
using BuildFeed.Model;

namespace BuildFeed.Admin.Controllers
{
    [Authorize(Roles = "Administrators")]
    [RouteArea("admin")]
    [RoutePrefix("meta")]
    public class MetaController : BaseController
    {
        private readonly MetaItem _mModel;

        public MetaController()
        {
            _mModel = new MetaItem();
        }

        [Route("")]
        public async Task<ActionResult> Index() => View(new MetaListing
        {
            CurrentItems = from i in await _mModel.Select()
                group i by i.Id.Type
                into b
                orderby b.Key.ToString()
                select b,

            NewItems = from i in (from l in await _mModel.SelectUnusedLabs()
                        select new MetaItemModel
                        {
                            Id = new MetaItemKey
                            {
                                Type = MetaType.Lab,
                                Value = l
                            }
                        }).Concat(from v in await _mModel.SelectUnusedVersions()
                        select new MetaItemModel
                        {
                            Id = new MetaItemKey
                            {
                                Type = MetaType.Version,
                                Value = v
                            }
                        })
                    .Concat(from y in await _mModel.SelectUnusedYears()
                        select new MetaItemModel
                        {
                            Id = new MetaItemKey
                            {
                                Type = MetaType.Year,
                                Value = y
                            }
                        })
                    .Concat(from y in await _mModel.SelectUnusedFamilies()
                        select new MetaItemModel
                        {
                            Id = new MetaItemKey
                            {
                                Type = MetaType.Family,
                                Value = y
                            }
                        })
                group i by i.Id.Type
                into b
                orderby b.Key.ToString()
                select b
        });

        [Route("create/{type}/{value}")]
        public ActionResult Create(MetaType type, string value) => View(new MetaItemModel
        {
            Id = new MetaItemKey
            {
                Type = type,
                Value = value
            }
        });

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create/{type}/{value}")]
        public async Task<ActionResult> Create(MetaItemModel meta)
        {
            if (ModelState.IsValid)
            {
                await _mModel.Insert(meta);
                return RedirectToAction(nameof(Index));
            }

            return View(meta);
        }

        [Route("edit/{type}/{value}")]
        public async Task<ActionResult> Edit(MetaType type, string value) => View(nameof(Create),
            await _mModel.SelectById(new MetaItemKey
            {
                Type = type,
                Value = value
            }));

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit/{type}/{value}")]
        public async Task<ActionResult> Edit(MetaItemModel meta)
        {
            if (ModelState.IsValid)
            {
                await _mModel.Update(meta);
                return RedirectToAction("Index");
            }

            return View(nameof(Create), meta);
        }
    }
}

BuildFeed/Areas/admin/Views/meta/create.cshtml
@using BuildFeed.Model
@model MetaItemModel
@{
    ViewBag.Title = $"Add metadata for {Model.Id.Value} | {InvariantTerms.SiteName}";
}

@section head
{
    <link href="~/Scripts/trumbowyg/ui/trumbowyg.min.css" rel="stylesheet" type="text/css" />
}

<h1>@($"Add metadata for {Model.Id.Value}")</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id.Type)
    @Html.HiddenFor(model => model.Id.Value)

    <div class="form-group">
        @Html.LabelFor(model => model.MetaDescription)
        <div class="wide-group">
            @Html.TextAreaFor(model => model.MetaDescription, new
            {
                rows = "4"
            })
            <div>
                <span id="meta-count">0</span> characters
                @Html.ValidationMessageFor(model => model.MetaDescription)
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PageContent)
        <div class="wide-group">
            @Html.TextAreaFor(model => model.PageContent)
            <div>
                @Html.ValidationMessageFor(model => model.PageContent)
            </div>
        </div>
    </div>

    <div class="form-group">
        <span class="label-placeholder"></span>
        <div>
            <input type="submit" value="Add metadata" />
        </div>
    </div>
}

@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="~/Scripts/trumbowyg/trumbowyg.min.js" type="text/javascript"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js" integrity="sha256-F6h55Qw6sweK+t7SiOJX+2bpSAa3b/fnlrVCJvmEj1A=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js" integrity="sha256-g1QKGxqsp+x5JkuN/JjHl96je2wztgS5Wo4h4c7gm9M=" crossorigin="anonymous"></script>

    <script type="text/javascript">
        function updateMetaCount()
        {
            var count = document.getElementById("@Html.IdFor(model => model.MetaDescription)").value.length;
            $("#meta-count").text(count.toFixed(0));
            if (count === 0)
            {
                $("#meta-count").attr("class", "");
            }
            else if (count < 160)
            {
                $("#meta-count").attr("class", "text-success");
            }
            else
            {
                $("#meta-count").attr("class", "text-danger");
            }
        }

        $(function()
        {
            $.trumbowyg.svgPath = "/Scripts/trumbowyg/ui/icons.svg";

            $("#@Html.IdFor(model => model.PageContent)")
                .trumbowyg({
                    autogrow: true,
                    btns: [
                        ['strong', 'em'],
                        '|', 'link',
                        '|', ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                        '|', ['unorderedList', 'orderedList'],
                        '|', 'viewHTML',
                        '|'
                    ]
                });

            $("#@Html.IdFor(model => model.MetaDescription)")
                .keyup(function()
                {
                    updateMetaCount();
                });

            updateMetaCount();
        });
    </script>
}

BuildFeed/Areas/admin/Views/meta/index.cshtml
@using BuildFeed.Admin.Models.ViewModel
@using BuildFeed.Model
@model MetaListing

@{
    ViewBag.Title = $"Manage metadata | {InvariantTerms.SiteName}";
}

<h1>Manage metadata</h1>
<ul>
    <li>@Html.ActionLink("Return to admin panel", nameof(RootController.Index), "Root")</li>
</ul>
<h3>Current items</h3>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th style="width: 50px"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var group in Model.CurrentItems)
    {
        <tr>
            <td colspan="3">
                <h4>@group.Key</h4>
            </td>
        </tr>
        foreach (MetaItemModel item in group)
        {
            <tr>
                <td>@item.Id.Value</td>
                <td>
                    @Html.ActionLink("Edit", nameof(MetaController.Edit), new
                    {
                        type = item.Id.Type,
                        value = item.Id.Value
                    }, new
                    {
                        @class = "button",
                        style = "width:50px"
                    })</td>
            </tr>
        }
    }
    </tbody>
</table>
<h3>Add new items</h3>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th style="width: 50px"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var group in Model.NewItems)
    {
        <tr>
            <td colspan="3">
                <h4>@group.Key</h4>
            </td>
        </tr>
        foreach (MetaItemModel item in group)
        {
            <tr>
                <td>@item.Id.Value</td>
                <td>
                    @Html.ActionLink("Create", nameof(MetaController.Create), new
                    {
                        type = item.Id.Type,
                        value = item.Id.Value
                    }, new
                    {
                        @class = "button",
                        style = "width:50px"
                    })</td>
            </tr>
        }
    }
    </tbody>
</table>