BuildFeed/Controllers/frontController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using BuildFeed.Code;
using BuildFeed.Model;
using BuildFeed.Model.View;
using OneSignal.RestAPIv3.Client;

namespace BuildFeed.Controllers
{
    public class FrontController : BaseController
    {
        public const int PAGE_SIZE = 72;

        private readonly BuildRepository _bModel;
        private readonly MetaItem _mModel;

        public FrontController()
        {
            _bModel = new BuildRepository();
            _mModel = new MetaItem();
        }

        [Route("", Order = 1)]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> Index()
        {
            ViewBag.Versions = await _bModel.SelectAllFamilies();
            ViewBag.Years = await _bModel.SelectAllYears();
            ViewBag.Sources = await _bModel.SelectAllSources();

            var items = await _bModel.SelectFrontPage();
            return View(nameof(Index), items);
        }

        [Route("page-{page:int:min(1)}/", Order = 0)]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "page", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> IndexPage(int page)
        {
            var buildGroups = await _bModel.SelectAllGroups(PAGE_SIZE, (page - 1) * PAGE_SIZE);

            ViewBag.PageNumber = page;
            ViewBag.PageCount =
                Math.Ceiling(Convert.ToDouble(await _bModel.SelectAllGroupsCount()) / Convert.ToDouble(PAGE_SIZE));

            if (ViewBag.PageNumber > ViewBag.PageCount)
            {
                return new HttpNotFoundResult();
            }

            return View("Pages", buildGroups);
        }

        [Route("group/{major}.{minor}.{number}.{revision}/", Order = 1)]
        [Route("group/{major}.{minor}.{number}/", Order = 5)]
        // for when there is no revision
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> ViewGroup(uint major, uint minor, uint number, uint? revision = null)
        {
            var bg = new BuildGroup
            {
                Major = major,
                Minor = minor,
                Build = number,
                Revision = revision
            };

            var builds = await _bModel.SelectGroup(bg);

            return builds.Count == 1
                ? RedirectToAction(nameof(ViewBuild),
                    new
                    {
                        id = builds.Single().Id
                    }) as ActionResult
                : View(new Tuple<BuildGroup, List<Build>>(bg, builds));
        }

        [Route("build/{id:guid}/", Name = "Build")]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> ViewBuild(Guid id)
        {
            Build b = await _bModel.SelectById(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            return View(b);
        }

        [Route("build/{id:long}/", Name = "Build (Legacy)")]
        public async Task<ActionResult> ViewBuild(long id)
        {
            Build b = await _bModel.SelectByLegacyId(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            return RedirectToAction(nameof(ViewBuild),
                new
                {
                    id = b.Id
                });
        }

        [Route("twitter/{id:guid}/", Name = "Twitter")]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [CustomContentType(ContentType = "image/png", Order = 2)]
        #endif
        public async Task<ActionResult> TwitterCard(Guid id)
        {
            Build b = await _bModel.SelectById(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            string path = Path.Combine(Server.MapPath("~/res/card/"), $"{b.Family}.png");
            bool backExists = System.IO.File.Exists(path);

            using (Bitmap bm = backExists
                ? new Bitmap(path)
                : new Bitmap(1120, 600))
            {
                using (Graphics gr = Graphics.FromImage(bm))
                {
                    gr.CompositingMode = CompositingMode.SourceOver;
                    gr.CompositingQuality = CompositingQuality.HighQuality;
                    gr.InterpolationMode = InterpolationMode.HighQualityBicubic;
                    gr.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
                    gr.SmoothingMode = SmoothingMode.HighQuality;
                    gr.PixelOffsetMode = PixelOffsetMode.HighQuality;

                    if (!backExists)
                    {
                        gr.FillRectangle(new SolidBrush(Color.FromArgb(0x24, 0x24, 0x23)), 0, 0, 1120, 600);
                    }

                    int left = 40;
                    using (var gp = new GraphicsPath())
                    {
                        foreach (char c in "BUILDFEED")
                        {
                            gp.AddString(c.ToString(),
                                new FontFamily("Segoe UI Semibold"),
                                0,
                                32,
                                new Point(left, 32),
                                StringFormat.GenericTypographic);

                            RectangleF bounds = gp.GetBounds();
                            left = Convert.ToInt32(bounds.Width);
                            left += 52;
                        }

                        gr.FillPath(Brushes.White, gp);
                    }

                    using (var gp = new GraphicsPath())
                    {
                        gp.AddString(b.Number.ToString(),
                            new FontFamily("Segoe UI Light"),
                            0,
                            260,
                            new Point(32, 114),
                            StringFormat.GenericTypographic);

                        RectangleF bounds = gp.GetBounds();
                        left = Convert.ToInt32(bounds.Width);
                        left += 44;

                        if (b.Revision.HasValue)
                        {
                            gp.AddString($".{b.Revision}",
                                new FontFamily("Segoe UI Light"),
                                0,
                                160,
                                new Point(left, 220),
                                StringFormat.GenericTypographic);
                        }

                        gr.DrawPath(new Pen(new SolidBrush(Color.FromArgb(0x24, 0x24, 0x23)), 4), gp);
                        gr.FillPath(Brushes.White, gp);
                    }

                    using (var gp = new GraphicsPath())
                    {
                        gp.AddString(
                            $"{MvcExtensions.GetDisplayTextForEnum(b.Family)} (NT {b.MajorVersion}.{b.MinorVersion})",
                            new FontFamily("Segoe UI Light"),
                            0,
                            48,
                            new Point(40, 80),
                            StringFormat.GenericTypographic);

                        gp.AddString(char.ConvertFromUtf32(0xf126),
                            new FontFamily("FontAwesome"),
                            0,
                            28,
                            new Point(46, 468),
                            StringFormat.GenericTypographic);
                        gp.AddString(b.Lab,
                            new FontFamily("Segoe UI Light"),
                            0,
                            40,
                            new Point(88, 450),
                            StringFormat.GenericTypographic);

                        if (b.BuildTime.HasValue)
                        {
                            gp.AddString(char.ConvertFromUtf32(0xf017),
                                new FontFamily("FontAwesome"),
                                0,
                                28,
                                new Point(40, 538),
                                StringFormat.GenericTypographic);
                            gp.AddString(
                                $"{b.BuildTime.Value.ToShortTimeString()} on {b.BuildTime.Value.ToLongDateString()}",
                                new FontFamily("Segoe UI Light"),
                                0,
                                40,
                                new Point(88, 520),
                                StringFormat.GenericTypographic);
                        }

                        gr.FillPath(Brushes.White, gp);
                    }

                    Response.ContentType = "image/png";
                    bm.Save(Response.OutputStream, ImageFormat.Png);
                }
            }

            return new EmptyResult();
        }

        [Route("twitter/{id:long}/", Name = "Twitter (Legacy)")]
        public async Task<ActionResult> TwitterCard(long id)
        {
            Build b = await _bModel.SelectByLegacyId(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

BuildFeed/Controllers/rssController.cs
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BuildFeed.Model;
using WilderMinds.RssSyndication;

namespace BuildFeed.Controllers
{
    public class RssController : BaseController
    {
        private const int RSS_SIZE = 25;
        private readonly BuildRepository _bModel;

        public RssController()
        {
            _bModel = new BuildRepository();
        }

        [Route("rss/compiled")]
        public async Task<ActionResult> Index()
        {
            var builds = await _bModel.SelectBuildsByCompileDate(RSS_SIZE);

            var feed = new Feed
            {
                Title = "BuildFeed RSS - Recently Compiled",
                Link = new Uri($"{Request.Url.Scheme}://{Request.Url.Authority}"),
                Items = (from build in builds
                    select new Item
                    {
                        Title = build.AlternateBuildString,
                        Link = new Uri(
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}"),
                        Permalink =
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}",
                        Categories = build.RssCategories,
                        PublishDate = DateTime.SpecifyKind(build.BuildTime.GetValueOrDefault(), DateTimeKind.Utc)
                    }).ToList()
            };

            return new ContentResult
            {
                Content = feed.Serialize(),
                ContentType = "application/rss+xml",
                ContentEncoding = Encoding.UTF8
            };
        }

        [Route("rss/added")]
        public async Task<ActionResult> Added()
        {
            var builds = await _bModel.SelectBuildsByAddedDate(RSS_SIZE);

            var feed = new Feed
            {
                Title = "BuildFeed RSS - Recently Added",
                Link = new Uri($"{Request.Url.Scheme}://{Request.Url.Authority}"),
                Items = (from build in builds
                    select new Item
                    {
                        Title = build.AlternateBuildString,
                        Link = new Uri(
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}"),
                        Permalink =
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}",
                        Categories = build.RssCategories,
                        PublishDate = DateTime.SpecifyKind(build.Added, DateTimeKind.Utc)
                    }).ToList()
            };

            return new ContentResult
            {
                Content = feed.Serialize(),
                ContentType = "application/rss+xml",
                ContentEncoding = Encoding.UTF8
            };
        }

        [Route("rss/leaked")]
        public async Task<ActionResult> Leaked()
        {
            var builds = await _bModel.SelectBuildsByLeakedDate(RSS_SIZE);

            var feed = new Feed
            {
                Title = "BuildFeed RSS - Recently Leaked",
                Link = new Uri($"{Request.Url.Scheme}://{Request.Url.Authority}"),
                Items = (from build in builds
                    select new Item
                    {
                        Title = build.AlternateBuildString,
                        Link = new Uri(
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}"),
                        Permalink =
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}",
                        Categories = build.RssCategories,
                        PublishDate = DateTime.SpecifyKind(build.LeakDate.GetValueOrDefault(), DateTimeKind.Utc)
                    }).ToList()
            };

            return new ContentResult
            {
                Content = feed.Serialize(),
                ContentType = "application/rss+xml",
                ContentEncoding = Encoding.UTF8
            };
        }

        [Route("rss/version")]
        public async Task<ActionResult> Version()
        {
            var builds = await _bModel.SelectBuildsByOrder(RSS_SIZE);

            var feed = new Feed
            {
                Title = "BuildFeed RSS - Highest Version",
                Link = new Uri($"{Request.Url.Scheme}://{Request.Url.Authority}"),
                Items = (from build in builds
                    select new Item
                    {
                        Title = build.AlternateBuildString,
                        Link = new Uri(
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}"),
                        Permalink =
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}",
                        Categories = build.RssCategories
                    }).ToList()
            };

            return new ContentResult
            {
                Content = feed.Serialize(),
                ContentType = "application/rss+xml",
                ContentEncoding = Encoding.UTF8
            };
        }

        [Route("rss/lab/{lab}")]
        public async Task<ActionResult> Lab(string lab)
        {
            var builds = await _bModel.SelectLab(lab, RSS_SIZE);

            var feed = new Feed
            {
                Title = $"BuildFeed RSS - {lab} Lab",
                Link = new Uri($"{Request.Url.Scheme}://{Request.Url.Authority}"),
                Items = (from build in builds
                    select new Item
                    {
                        Title = build.AlternateBuildString,
                        Link = new Uri(
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}"),
                        Permalink =
                            $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Action(nameof(FrontController.ViewBuild), new { controller = "Front", id = build.Id })}",
                        Categories = build.RssCategories
                    }).ToList()
            };

            return new ContentResult
            {
                Content = feed.Serialize(),
                ContentType = "application/rss+xml",
                ContentEncoding = Encoding.UTF8
            };
        }
    }
}

BuildFeed/Views/front/AddBulk.cshtml
@using BuildFeed.Controllers
@using BuildFeed.Model
@using BuildFeed.Model.View
@model BulkAddition

@{
    ViewBag.Title = $"{VariantTerms.Common_AddBulk} | {InvariantTerms.SiteName}";
}

<h1>@VariantTerms.Common_AddBulk</h1>

@if (ViewBag.Results != null)
{
    <p>@VariantTerms.Bulk_Success</p>
    <ul>
        @foreach (Build b in ViewBag.Results)
        {
            <li>
                <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                         {
                             id = b.Id
                         })" target="_blank">
                    @b.AlternateBuildString</a>
            </li>
        }
    </ul>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <span class="label-placeholder"></span>
        <div>
            @VariantTerms.Bulk_Instructions
        </div>
    </div>

    <div class="form-group">
        <label for="@Html.IdFor(m => m.Builds)">@VariantTerms.Bulk_Builds</label>
        <div>
            @Html.TextAreaFor(m => m.Builds, new
            {
                rows = 10
            })
        </div>
    </div>

    <div class="form-group">
        <span class="label-placeholder"></span>
        <div>
            <label for="@Html.IdFor(m => m.SendNotifications)">
                @Html.CheckBoxFor(m => m.SendNotifications)
                @VariantTerms.Bulk_SendNotifications
            </label>
        </div>
    </div>

    <div class="form-group">
        <span class="label-placeholder"></span>
        <div>
            <input type="submit" value="@VariantTerms.Bulk_AddBuilds" class="button" />
        </div>
    </div>
}

BuildFeed/Views/front/Pages.cshtml
@using BuildFeed.Code
@using BuildFeed.Controllers
@using BuildFeed.Model.View
@using Humanizer
@model IEnumerable<FrontBuildGroup>
@{
    ViewBag.Title = $"{string.Format(VariantTerms.Front_HomepageH1, InvariantTerms.ProductName)} {string.Format(VariantTerms.Common_TitlePage, (int)ViewBag.PageNumber)} | {InvariantTerms.SiteName}";
}

@section head
{
    <meta name="robots" content="noindex, follow" />
}

<h1>@string.Format(VariantTerms.Front_HomepageH1, InvariantTerms.ProductName)</h1>
<h3>@VariantTerms.Front_Listing</h3>
<div class="build-group-listing">
    @foreach (FrontBuildGroup group in Model)
    {
        <div class="build-group">
            <h3 class="build-group-title">
                <a href="@Url.Action(nameof(FrontController.ViewGroup), new
                         {
                             major = group.Key.Major,
                             minor = group.Key.Minor,
                             number = group.Key.Build,
                             revision = group.Key.Revision
                         })">
                    @group.Key.ToString()
                </a>
            </h3>
            @if (group.LastBuild.HasValue)
            {
                <p class="build-group-p">
                    @{
                        DateTime maxDate = group.LastBuild.Value;
                        if (maxDate.AddDays(28) > DateTime.Now)
                        {
                            <span title="@maxDate.ToLongDateWithoutDay()">
                                <i class="fa fa-calendar fa-fw"></i> @maxDate.Humanize()</span>
                        }
                        else
                        {
                            <span title="@maxDate.Humanize()">
                                <i class="fa fa-calendar fa-fw"></i> @maxDate.ToLongDateWithoutDay()</span>
                        }
                    }
                </p>
            }
            <p class="build-group-p">
                <i class="fa fa-server fa-fw"></i> @string.Format(VariantTerms.Front_NumOfBuilds, group.BuildCount)
            </p>
        </div>
    }
    <div class="build-group-empty"></div>
    <div class="build-group-empty"></div>
    <div class="build-group-empty"></div>
    <div class="build-group-empty"></div>
    <div class="build-group-empty"></div>
</div>
@PaginationHelpers.PaginationBlock((int)ViewBag.PageNumber, (int)ViewBag.PageCount, nameof(FrontController.Index), ViewContext.RouteData.Values)

BuildFeed/Views/front/index.cshtml
@using BuildFeed.Code
@using BuildFeed.Controllers
@using BuildFeed.Model
@using BuildFeed.Model.View
@model Dictionary<ProjectFamily, FrontPage>
@{
    ViewBag.Title = string.Format(VariantTerms.Front_HomeH1, InvariantTerms.SiteName);
}

@section Head
{
    <meta name="description" content="Learn what Dona Sarkar won&apos;t tell you. Keep up to date with the latest Microsoft Windows developments with BuildFeed, the comprehensive build tracker." />
    <link rel="alternate" type="application/rss+xml" title="Latest additions - RSS" href="@Url.Action(nameof(RssController.Added), "Rss")" />
}

<h1>@string.Format(VariantTerms.Front_HomeH1, InvariantTerms.SiteName)</h1>

<h3>@VariantTerms.Front_LatestBuilds</h3>
<a href="@Url.Action("IndexPage", new
         {
             Page = 1
         })" class="latest-full">
    @VariantTerms.Front_FullBuildListing
</a>
<div class="trim-wrapper">
    <div class="latest-family-wrapper">
        @foreach (var item in Model)
        {
            FrontPage family = item.Value;

            <div class="latest-family">
                <h3>@MvcExtensions.GetDisplayTextForEnum(item.Key)</h3>
                <div class="latest-flex">
                    @if (family.CurrentCanary != null && family.CurrentCanary.Id != family.CurrentInsider?.Id)
                    {
                        <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                                 {
                                     family.CurrentCanary.Id
                                 })" class="latest-flex-item latest-flex-red">
                            @BuildHelpers.LatestBuild(VariantTerms.Front_CurrentCanary, family.CurrentCanary)
                        </a>
                    }
                    @if (family.CurrentInsider != null && family.CurrentInsider.Id != family.CurrentRelease?.Id)
                    {
                        <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                                 {
                                     family.CurrentInsider.Id
                                 })" class="latest-flex-item latest-flex-yellow">
                            @BuildHelpers.LatestBuild(VariantTerms.Front_CurrentInsider, family.CurrentInsider)
                        </a>
                    }
                    @if (family.CurrentRelease != null)
                    {
                        <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                                 {
                                     family.CurrentRelease.Id
                                 })" class="latest-flex-item latest-flex-blue">
                            @BuildHelpers.LatestBuild(VariantTerms.Front_CurrentRelease, family.CurrentRelease)
                        </a>
                    }
                    @if (family.CurrentAnalog != null)
                    {
                        <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                                 {
                                     family.CurrentAnalog.Id
                                 })" class="latest-flex-item latest-flex-purple">
                            @BuildHelpers.LatestBuild(VariantTerms.Front_CurrentAnalog, family.CurrentAnalog)
                        </a>
                    }
                    @if (family.CurrentXbox != null)
                    {
                        <a href="@Url.Action(nameof(FrontController.ViewBuild), new
                                 {
                                     family.CurrentXbox.Id
                                 })" class="latest-flex-item latest-flex-green">
                            @BuildHelpers.LatestBuild(VariantTerms.Front_CurrentXbox, family.CurrentXbox)
                        </a>
                    }
                </div>
            </div>
        }
    </div>
</div>
<h3>@VariantTerms.Search_BuildFeed</h3>
<div class="build-group-listing">
    <div class="build-group">
        <h3 class="build-group-title">
            <span>@VariantTerms.Search_Version</span>
        </h3>
        <div class="form-group">
            <div class="group-input-button">
                <select id="search-version">
                    @{
                        ProjectFamily[] versions = ViewBag.Versions;
                        foreach (ProjectFamily version in versions)
                        {
                            <option value="@Url.Action(nameof(FrontController.ViewFamily), "Front", new
                                           {
                                               family = version
                                           })">
                                @MvcExtensions.GetDisplayDescriptionForEnum(version)
                            </option>
                        }
                    }
                </select>
                <button onclick="window.location = document.getElementById('search-version').value;return false;" title="@VariantTerms.Search_Title">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="build-group">
        <h3 class="build-group-title">
            <span>@VariantTerms.Search_Year</span>
        </h3>
        <div class="form-group">
            <div class="group-input-button">
                <select id="search-year">
                    @{
                        int[] years = ViewBag.Years;
                        foreach (int year in years)
                        {
                            <option value="@Url.Action(nameof(FrontController.ViewYear), "Front", new
                                           {
                                               year
                                           })">
                                @year
                            </option>
                        }
                    }
                </select>
                <button onclick="window.location = document.getElementById('search-year').value;return false;" title="@VariantTerms.Search_Title">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="build-group">
        <h3 class="build-group-title">
            <span>@VariantTerms.Search_Source</span>
        </h3>
        <div class="form-group">
            <div class="group-input-button">
                <select id="search-source">
                    @{
                        TypeOfSource[] sources = ViewBag.Sources;
                        foreach (TypeOfSource source in sources)
                        {
                            <option value="@Url.Action(nameof(FrontController.ViewSource), "Front", new
                                           {
                                               source
                                           })">
                                @MvcExtensions.GetDisplayTextForEnum(source)
                            </option>
                        }
                    }
                </select>
                <button onclick="window.location = document.getElementById('search-source').value;return false;" title="@VariantTerms.Search_Title">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<h3>@VariantTerms.Front_Share</h3>
<div class="addthis_sharing_toolbox"></div>
<br />
<h3>@string.Format(VariantTerms.Front_AboutSite, InvariantTerms.SiteName)</h3>
<h4>@VariantTerms.About_Q1</h4>
<p>@VariantTerms.About_A1</p>
<h4>@VariantTerms.About_Q2</h4>
<p>@VariantTerms.About_A2</p>
<h4>@VariantTerms.About_Q3</h4>
<p>@VariantTerms.About_A3</p>

@section Scripts
{
    <script type="application/ld+json">
        {
            "@("@")context": "http://schema.org",
            "@("@")type": "Organization",
            "name": "BuildFeed",
            "url": "https://buildfeed.net/",
            "logo": "https://buildfeed.net/res/ico/notify.png",
            "sameAs": [
                "https://twitter.com/buildfeed"
            ]
        }
    </script>
}