BuildFeed/Controllers/frontController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using BuildFeed.Code;
using BuildFeed.Model;
using BuildFeed.Model.View;
using OneSignal.RestAPIv3.Client;

namespace BuildFeed.Controllers
{
    public class FrontController : BaseController
    {
        public const int PAGE_SIZE = 72;

        private readonly BuildRepository _bModel;
        private readonly MetaItem _mModel;

        public FrontController()
        {
            _bModel = new BuildRepository();
            _mModel = new MetaItem();
        }

        [Route("", Order = 1)]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> Index()
        {
            ViewBag.Versions = await _bModel.SelectAllFamilies();
            ViewBag.Years = await _bModel.SelectAllYears();
            ViewBag.Sources = await _bModel.SelectAllSources();

            var items = await _bModel.SelectFrontPage();
            return View(nameof(Index), items);
        }

        [Route("page-{page:int:min(1)}/", Order = 0)]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "page", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> IndexPage(int page)
        {
            var buildGroups = await _bModel.SelectAllGroups(PAGE_SIZE, (page - 1) * PAGE_SIZE);

            ViewBag.PageNumber = page;
            ViewBag.PageCount =
                Math.Ceiling(Convert.ToDouble(await _bModel.SelectAllGroupsCount()) / Convert.ToDouble(PAGE_SIZE));

            if (ViewBag.PageNumber > ViewBag.PageCount)
            {
                return new HttpNotFoundResult();
            }

            return View("Pages", buildGroups);
        }

        [Route("group/{major}.{minor}.{number}.{revision}/", Order = 1)]
        [Route("group/{major}.{minor}.{number}/", Order = 5)]
        // for when there is no revision
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> ViewGroup(uint major, uint minor, uint number, uint? revision = null)
        {
            var bg = new BuildGroup
            {
                Major = major,
                Minor = minor,
                Build = number,
                Revision = revision
            };

            var builds = await _bModel.SelectGroup(bg);

            return builds.Count == 1
                ? RedirectToAction(nameof(ViewBuild),
                    new
                    {
                        id = builds.Single().Id
                    }) as ActionResult
                : View(new Tuple<BuildGroup, List<Build>>(bg, builds));
        }

        [Route("build/{id:guid}/", Name = "Build")]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [OutputCachePush(Order = 2)]
        #endif
        public async Task<ActionResult> ViewBuild(Guid id)
        {
            Build b = await _bModel.SelectById(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            return View(b);
        }

        [Route("build/{id:long}/", Name = "Build (Legacy)")]
        public async Task<ActionResult> ViewBuild(long id)
        {
            Build b = await _bModel.SelectByLegacyId(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            return RedirectToAction(nameof(ViewBuild),
                new
                {
                    id = b.Id
                });
        }

        [Route("twitter/{id:guid}/", Name = "Twitter")]
        #if !DEBUG
        [OutputCache(Duration = 600, VaryByParam = "none", VaryByCustom = "userName;lang;theme")]
        [CustomContentType(ContentType = "image/png", Order = 2)]
        #endif
        public async Task<ActionResult> TwitterCard(Guid id)
        {
            Build b = await _bModel.SelectById(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

            string path = Path.Combine(Server.MapPath("~/res/card/"), $"{b.Family}.png");
            bool backExists = System.IO.File.Exists(path);

            using (Bitmap bm = backExists
                ? new Bitmap(path)
                : new Bitmap(1120, 600))
            {
                using (Graphics gr = Graphics.FromImage(bm))
                {
                    gr.CompositingMode = CompositingMode.SourceOver;
                    gr.CompositingQuality = CompositingQuality.HighQuality;
                    gr.InterpolationMode = InterpolationMode.HighQualityBicubic;
                    gr.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
                    gr.SmoothingMode = SmoothingMode.HighQuality;
                    gr.PixelOffsetMode = PixelOffsetMode.HighQuality;

                    if (!backExists)
                    {
                        gr.FillRectangle(new SolidBrush(Color.FromArgb(0x24, 0x24, 0x23)), 0, 0, 1120, 600);
                    }

                    int left = 40;
                    using (var gp = new GraphicsPath())
                    {
                        foreach (char c in "BUILDFEED")
                        {
                            gp.AddString(c.ToString(),
                                new FontFamily("Segoe UI Semibold"),
                                0,
                                32,
                                new Point(left, 32),
                                StringFormat.GenericTypographic);

                            RectangleF bounds = gp.GetBounds();
                            left = Convert.ToInt32(bounds.Width);
                            left += 52;
                        }

                        gr.FillPath(Brushes.White, gp);
                    }

                    using (var gp = new GraphicsPath())
                    {
                        gp.AddString(b.Number.ToString(),
                            new FontFamily("Segoe UI Light"),
                            0,
                            260,
                            new Point(32, 114),
                            StringFormat.GenericTypographic);

                        RectangleF bounds = gp.GetBounds();
                        left = Convert.ToInt32(bounds.Width);
                        left += 44;

                        if (b.Revision.HasValue)
                        {
                            gp.AddString($".{b.Revision}",
                                new FontFamily("Segoe UI Light"),
                                0,
                                160,
                                new Point(left, 220),
                                StringFormat.GenericTypographic);
                        }

                        gr.DrawPath(new Pen(new SolidBrush(Color.FromArgb(0x24, 0x24, 0x23)), 4), gp);
                        gr.FillPath(Brushes.White, gp);
                    }

                    using (var gp = new GraphicsPath())
                    {
                        gp.AddString(
                            $"{MvcExtensions.GetDisplayTextForEnum(b.Family)} (NT {b.MajorVersion}.{b.MinorVersion})",
                            new FontFamily("Segoe UI Light"),
                            0,
                            48,
                            new Point(40, 80),
                            StringFormat.GenericTypographic);

                        gp.AddString(char.ConvertFromUtf32(0xf126),
                            new FontFamily("FontAwesome"),
                            0,
                            28,
                            new Point(46, 468),
                            StringFormat.GenericTypographic);
                        gp.AddString(b.Lab,
                            new FontFamily("Segoe UI Light"),
                            0,
                            40,
                            new Point(88, 450),
                            StringFormat.GenericTypographic);

                        if (b.BuildTime.HasValue)
                        {
                            gp.AddString(char.ConvertFromUtf32(0xf017),
                                new FontFamily("FontAwesome"),
                                0,
                                28,
                                new Point(40, 538),
                                StringFormat.GenericTypographic);
                            gp.AddString(
                                $"{b.BuildTime.Value.ToShortTimeString()} on {b.BuildTime.Value.ToLongDateString()}",
                                new FontFamily("Segoe UI Light"),
                                0,
                                40,
                                new Point(88, 520),
                                StringFormat.GenericTypographic);
                        }

                        gr.FillPath(Brushes.White, gp);
                    }

                    Response.ContentType = "image/png";
                    bm.Save(Response.OutputStream, ImageFormat.Png);
                }
            }

            return new EmptyResult();
        }

        [Route("twitter/{id:long}/", Name = "Twitter (Legacy)")]
        public async Task<ActionResult> TwitterCard(long id)
        {
            Build b = await _bModel.SelectByLegacyId(id);
            if (b == null)
            {
                return new HttpNotFoundResult();
            }

BuildFeed/Views/support/credits.cshtml
@using System.Globalization
@{
    ViewBag.Title = $"{VariantTerms.Common_Credits} | {InvariantTerms.SiteName}";
}

<h1>@VariantTerms.Common_Credits</h1>

<dl class="credits-list">
    <dt>BuildFeed Team</dt>
    <dd>
        Thomas Hounsell&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/tomhounsell">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Nick (ultrawindows)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/nickurtnl">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Ahmed (airportsfan)
    </dd>
    <dd>
        Lukas (tfwboredom)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/tfwboredom">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Soorya (fakirmeditation)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/fakirmeditation">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Chris (Chris123NT)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Chris123NT">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
</dl>
<div class="credits-wrapper">
<dl class="credits-list">
    <dt>Arabic (@CultureInfo.GetCultureInfo("ar").NativeName) Translation</dt>
    <dd>
        Ahmed (airportsfan)
    </dd>
    <dt>Bengali (@CultureInfo.GetCultureInfo("bn").NativeName) Translation</dt>
    <dd>
        Mehedi Hassan&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/mehedih_">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Czech (@CultureInfo.GetCultureInfo("cs").NativeName) Translation</dt>
    <dd>
        David (rezedus)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/rezedus">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>German (@CultureInfo.GetCultureInfo("de").NativeName) Translation</dt>
    <dd>
        The Dhel&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/The_Dhel">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Christopher&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/evil_pro_">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Greek (@CultureInfo.GetCultureInfo("el").NativeName) Translation</dt>
    <dd>Hacker?pcs</dd>
    <dd>
        Sotiris Michail&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/SnakeOnStick">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Spanish (@CultureInfo.GetCultureInfo("es").NativeName) Translation</dt>
    <dd>Nightsteed</dd>
    <dd>
        Ben Ward&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/_BenW_">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Meober Whagby&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/ultimofriki">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Farsi (@CultureInfo.GetCultureInfo("fa").NativeName) Translation</dt>
    <dd>
        Niloo&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Niloo0937">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Finnish (@CultureInfo.GetCultureInfo("fi").NativeName) Translation</dt>
    <dd>
        Daniel Gurney (wheatley)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Daniel_Gurney0">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>French (@CultureInfo.GetCultureInfo("fr").NativeName) Translation</dt>
    <dd>
        CgSYannick&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/YannickTHFR">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Gustave M.&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/gus33000">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Christophe Lavalle&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/ChristopheLav">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Croatian (@CultureInfo.GetCultureInfo("hr").NativeName) Translation</dt>
    <dd>
        Mario Bešen&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/mariobesen">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Hebrew (@CultureInfo.GetCultureInfo("he").NativeName) Translation</dt>
    <dd>
        David Fainshtein&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/david_f">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Indonesian (@CultureInfo.GetCultureInfo("id").NativeName) Translation</dt>
    <dd>Andreas</dd>
    <dt>Italian (@CultureInfo.GetCultureInfo("it").NativeName) Translation</dt>
    <dd>
        Meober Whagby&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/ultimofriki">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Simone Nataz&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/djnataz">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Japanese (@CultureInfo.GetCultureInfo("ja").NativeName) Translation</dt>
    <dd>
        parly&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://github.com/parly">
            <i class="fa fa-github"></i>
        </a>
    </dd>
    <dt>Korean (@CultureInfo.GetCultureInfo("ko").NativeName) Translation</dt>
    <dd>qta3426</dd>
    <dd>
        SD SkyKlouD&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/_SDSkyKlouD">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
</dl>
<dl class="credits-list">
    <dt>Lithuanian (@CultureInfo.GetCultureInfo("lt").NativeName) Translation</dt>
    <dd>
        Super User&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Superb_User">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Dutch (@CultureInfo.GetCultureInfo("nl").NativeName) Translation</dt>
    <dd>
        Nick (ultrawindows)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/nickurtnl">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Polish (@CultureInfo.GetCultureInfo("pl").NativeName) Translation</dt>
    <dd>
        piotrulos&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/piotrulos">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        dzaggiel&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/dzaggiel">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Portuguese (@CultureInfo.GetCultureInfo("pt").NativeName) Translation</dt>
    <dd>OBattler</dd>
    <dt>Portugese - Brazilian (@CultureInfo.GetCultureInfo("pt-br").NativeName) Translation</dt>
    <dd>RichardG</dd>
    @*<dt>Pseudo-localisation (@System.Globalization.CultureInfo.GetCultureInfo("qps-ploc").NativeName) Translation</dt>
      <dd>Thomas Hounsell, with&ensp;<a target="_blank" rel="nofollow noopener" href="http://www.pseudolocalize.com/"><i class="fa fa-globe"></i> Pseudolocalize!</a></dd>*@
    <dt>Romanian (@CultureInfo.GetCultureInfo("ro").NativeName) Translation</dt>
    <dd>
        ovctvct&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://www.youtube.com/channel/UC9AC01rKiwDhVPvAsT93rjw">
            <i class="fa fa-youtube"></i>
        </a>
    </dd>
    <dt>Russian (@CultureInfo.GetCultureInfo("ru").NativeName) Translation</dt>
    <dd>
        Roman (rlinev)&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/rlinev">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>
        Fuhrer_Adolf&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Fuhrer_Adolf">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Slovak (@CultureInfo.GetCultureInfo("sk").NativeName) Translation</dt>
    <dd>
        Lukas&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/tfwboredom">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Slovenian (@CultureInfo.GetCultureInfo("sl").NativeName) Translation</dt>
    <dd>Overdoze</dd>
    <dt>Swedish (@CultureInfo.GetCultureInfo("sv").NativeName) Translation</dt>
    <dd>
        mrpijey&ensp;
        <a target="_blank" rel="nofollow noopener" href="http://www.mrpijey.net/">
            <i class="fa fa-globe"></i>
        </a>
    </dd>
    <dt>Turkish (@CultureInfo.GetCultureInfo("tr").NativeName) Translation</dt>
    <dd>
        Furkan AKÇATEPE&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/FurkanAKATEPE">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dd>Can Taşan</dd>
    <dd>
        Duhan Ömür&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/BilgisyrKurdu16">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Ukrainian (@CultureInfo.GetCultureInfo("uk").NativeName) Translation</dt>
    <dd>
        Fuhrer_Adolf&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/Fuhrer_Adolf">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Vietnamese (@CultureInfo.GetCultureInfo("vi").NativeName) Translation</dt>
    <dd>
        Trần Kim Long Hải&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/trankimlonghai">
            <i class="fa fa-twitter"></i>
        </a>
    </dd>
    <dt>Chinese - Simplified (@CultureInfo.GetCultureInfo("zh-hans").NativeName) Translation</dt>
    <dd>
        Zheng He&ensp;
        <a target="_blank" rel="nofollow noopener" href="http://www.betaworld.cn/">
            <i class="fa fa-globe"></i>
        </a>
    </dd>
    <dt>Chinese - Traditional (@CultureInfo.GetCultureInfo("zh-hant").NativeName) Translation</dt>
    <dd>
        Andrew Huang&ensp;
        <a target="_blank" rel="nofollow noopener" href="https://twitter.com/AndrewDev8383">
            <i class="fa fa-twitter"></i>
        </a>&ensp;
        <a target="_blank" rel="nofollow noopener" href="http://isite.tw/">
            <i class="fa fa-globe"></i>
        </a>
    </dd>
    <dd>
        GT Wang&ensp;
        <a target="_blank" rel="nofollow noopener" href="http://mkvq.blogspot.com/">
            <i class="fa fa-globe"></i>
        </a>
    </dd>
</dl>
</div>

BuildFeed/Views/support/rss.cshtml
@{
    ViewBag.Title = $"{VariantTerms.Common_RssFeeds} | {InvariantTerms.SiteName}";
}

<h1>@VariantTerms.Common_RssFeeds</h1>

<ul>
    <li>
        <a href="@Url.Action("Index", new
                 {
                     controller = "Rss"
                 })" title="@VariantTerms.Support_RecentlyCompiled">
            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyCompiled</a>
    </li>
    <li>
        <a href="@Url.Action("Leaked", new
                 {
                     controller = "Rss"
                 })" title="@VariantTerms.Support_RecentlyLeaked">
            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyLeaked</a>
    </li>
    <li>
        <a href="@Url.Action("Added", new
                 {
                     controller = "Rss"
                 })" title="@VariantTerms.Support_RecentlyAdded">
            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyAdded</a>
    </li>
    <li>
        <a href="@Url.Action("Version", new
                 {
                     controller = "Rss"
                 })" title="@VariantTerms.Support_HighestVersion">
            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_HighestVersion</a>
    </li>
    <li>
        <a href="#rss-labs" data-toggle="collapse">@VariantTerms.Search_Lab</a>
        <ul id="rss-labs" class="collapse">
            @foreach (string lab in ViewBag.Labs)
            {
                <li>
                    <a href="@Url.Action("Lab", new
                             {
                                 controller = "Rss",
                                 lab
                             })" title="@lab">
                        <i class="fa fa-sm fa-rss"></i> @lab</a>
                </li>
            }
        </ul>
    </li>
</ul>

BuildFeed/Views/support/sitemap.cshtml
@using BuildFeed.Controllers
@using BuildFeed.Model.View
@model SitemapData
@{
    ViewBag.Title = $"{VariantTerms.Common_Sitemap} | {InvariantTerms.SiteName}";
}

<h1>@VariantTerms.Common_Sitemap</h1>

<ul>
    <li>
        @Html.ActionLink("BuildFeed", nameof(FrontController.Index), "Front")
        <ul>
            <li>
                <a href="#sitemap-builds">Builds</a>
                <ul id="sitemap-builds">
                    @foreach (SitemapDataBuildGroup buildGroup in Model.Builds)
                    {
                        <li>
                            @Html.ActionLink(buildGroup.Id.ToString(), "ViewGroup", new
                            {
                                controller = "Front",
                                major = buildGroup.Id.Major,
                                minor = buildGroup.Id.Minor,
                                number = buildGroup.Id.Build,
                                revision = buildGroup.Id.Revision
                            })
                            <ul>
                                @foreach (SitemapDataBuild build in buildGroup.Builds)
                                {
                                    <li>
                                        @Html.ActionLink(build.Name, "ViewBuild", new
                                        {
                                            controller = "Front",
                                            id = build.Id
                                        })</li>
                                }
                            </ul>
                        </li>
                    }
                </ul>
            </li>
            @foreach (var item in Model.Actions)
            {
                <li>
                    <a href="#sitemap-@item.Key.ToLower()">@item.Key</a>
                    <ul id="sitemap-@item.Key.ToLower()">
                        @foreach (SitemapPagedAction action in item.Value)
                        {
                            if (string.IsNullOrEmpty(action.Name))
                            {
                                <li>@Html.ActionLink("Page 1", action.Action, action.UrlParams)</li>
                                for (int i = 2; i <= action.Pages; i++)
                                {
                                    RouteValueDictionary urlParams = action.UrlParams;
                                    urlParams["page"] = i;
                                    <li>@Html.ActionLink($"Page {i}", action.Action + "Page", urlParams)</li>
                                }
                            }
                            else
                            {
                                <li>
                                    <a href="#sitemap-@action.UniqueId">@action.Name</a>
                                    <ul id="sitemap-@action.UniqueId">
                                        <li>@Html.ActionLink("Page 1", action.Action, action.UrlParams)</li>
                                        @for (int i = 2; i <= action.Pages; i++)
                                        {
                                            RouteValueDictionary urlParams = action.UrlParams;
                                            urlParams["page"] = i;
                                            <li>@Html.ActionLink($"Page {i}", action.Action + "Page", urlParams)</li>
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                </li>
            }
            <li>
                <a href="#sitemap-rss">@VariantTerms.Common_RssFeeds</a>
                <ul id="sitemap-rss">
                    <li>
                        <a href="@Url.Action("Index", new
                                 {
                                     controller = "Rss"
                                 })" title="@VariantTerms.Support_RecentlyCompiled">
                            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyCompiled</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Leaked", new
                                 {
                                     controller = "Rss"
                                 })" title="@VariantTerms.Support_RecentlyLeaked">
                            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyLeaked</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Added", new
                                 {
                                     controller = "Rss"
                                 })" title="@VariantTerms.Support_RecentlyAdded">
                            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_RecentlyAdded</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Version", new
                                 {
                                     controller = "Rss"
                                 })" title="@VariantTerms.Support_HighestVersion">
                            <i class="fa fa-sm fa-rss"></i> @VariantTerms.Support_HighestVersion</a>
                    </li>
                    <li>
                        <a href="#rss-labs">@VariantTerms.Model_LabString</a>
                        <ul id="rss-labs">
                            @foreach (string lab in Model.Labs)
                            {
                                <li>
                                    <a href="@Url.Action("Lab", new
                                             {
                                                 controller = "Rss",
                                                 lab
                                             })" title="@lab">
                                        <i class="fa fa-sm fa-rss"></i> @lab</a>
                                </li>
                            }
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>